<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE facturas[
<!ELEMENT facturas (factura*)>
<!-- etiqueta factura-->
<!ELEMENT factura (datos_cliente, datos_factura)>
<!-- etiquete de los datos del cliente-->
<!ELEMENT datos_cliente (nombre, apellido, apellido, dni, tfno)>
    <!ATTLIST datos_cliente ident ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT tfno (#PCDATA)>
<!-- etiquetas datos factura-->
<!ELEMENT datos_factura (resguardo, (alquileres | compras | (alquileres, compras)))>
<!-- etiqueta del resguardo-->
<!ELEMENT resguardo (forma_pago, importe_total)>
<!ELEMENT forma_pago (#PCDATA)>
<!ELEMENT importe_total (#PCDATA)>
<!-- etiqueta de los alquileres-->
<!ELEMENT alquileres (fecha, peliculas)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT peliculas (pelicula+)>
<!-- etiqueta peliculas-->
<!ELEMENT pelicula (titulo, genero, duracion, actores)>
    <!ATTLIST pelicula identificador ID #REQUIRED>
    <!ATTLIST pelicula valoracion CDATA #REQUIRED>
    <!ATTLIST pelicula caratula ENTITY #IMPLIED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT actores (actor, actor, actor)>
<!ELEMENT actor (nombre, apellido, apellido)>
<!-- etiquetas compras-->
<!ELEMENT compras (dvds | cintas | (dvd, cintas))>
<!ELEMENT dvds (dvd+)>
<!ELEMENT dvd (extras?, titulo, fecha_salida_mercado)>
<!ELEMENT extras EMPTY>
<!ELEMENT fecha_salida_mercado (#PCDATA)>
<!ELEMENT cintas (cinta+)>
<!ELEMENT cinta (titulo, formato, rebobinado?)>
<!ELEMENT formato (#PCDATA)>
<!ELEMENT rebobinado EMPTY>
]>

<facturas>
    <factura>
        <datos_cliente ident="a01">
            <nombre>Olga</nombre>
            <apellido>García</apellido>
            <apellido>Blázquez</apellido>
            <dni>123456789A</dni>
            <tfno>987654321</tfno>
        </datos_cliente>
        <datos_factura>
            <resguardo>
                <forma_pago>efectivo</forma_pago>
                <importe_total>24</importe_total>
            </resguardo>
            <alquileres>
                <fecha>1/2/22</fecha>
                <peliculas>
                    <pelicula identificador="a148" caratula="foto_001" valoracion="7.5">
                        <titulo>Titanic</titulo>
                        <genero>romántica</genero>
                        <duracion>80min</duracion>
                        <actores>
                            <actor>
                                <nombre>Manuel</nombre>
                                <apellido>Suarez</apellido>
                                <apellido>López</apellido>
                            </actor>
                            <actor>
                                <nombre>Will</nombre>
                                 <apellido>Farrel</apellido>
                                 <apellido></apellido>
                            </actor>  
                            <actor>
                                <nombre>Vince</nombre>
                                <apellido>Vaughn</apellido>
                                 <apellido></apellido> 
                            </actor>  
                        </actores>
                    </pelicula>
                </peliculas>
            </alquileres>
            <compras>
                <dvds>
                    <dvd>
                        <extras/>
                        <titulo>Scream</titulo>
                        <fecha_salida_mercado>1996</fecha_salida_mercado>
                    </dvd>
                </dvds>
                <cintas>
                    <cinta>
                        <titulo>Pretty Woman</titulo>
                        <formato>VHS</formato>
                    </cinta>
                </cintas>
            </compras>
        </datos_factura>
    </factura>
</facturas>
